### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by gingerbeardman** [rafaelmoraes994/HanafudaGameiOS#1]
Hi, this looks really interesting — what's its status?

I can build and get to the table screen but it doesn't "play".

![screen shot 2018-08-07 at 20 38 10](https://user-images.githubusercontent.com/49612/43798228-d746bbde-9a81-11e8-9838-fbfe9239d2ab.png)

**Comment by rafaelmoraes994** [comment]
Hi, thank you for the interest!
I started this project with the goal of improving my Swift skills, as I was a beginner at the time. I always wanted to create a game app and as I am a fan of the Koi-Koi game, I decided that it was a great idea for the challenge. Shortly after I started the project, I got a job opportunity which today takes almost all of my time, so unfortunatly this project is on hold for the moment. I will definitely come back to this, but I can't really say when.

**Comment by gingerbeardman** [comment]
Good luck with your job! I really like the approach you have taken with this. I'll see if I have some time to add to it

**Comment by gingerbeardman** [comment]
Hey Rafael, I remembered this project today when browsing my old downloads. I thought you might like to drop by the Hanafuda Discord if you still like Koi-Koi https://discordapp.com/invite/7Bk3YQT

**Comment by gingerbeardman** [comment]
@rafaelmoraes994  where are your card images from? Are they scans?

**Comment by rafaelmoraes994** [comment]
Hello Matt!
Sorry for late response, I got them from some ramdom website, cant remember
which one, its been a long time but I think its not that hard to find.

Att,
Rafael

Em seg, 9 de dez de 2019 06:13, Matt Sephton <notifications@github.com>
escreveu:
